
server:
  port: 8888

fcm:
  service-account-file: C:\\Users\\zhijiang\\Documents\\Projects\\toolchain\\ift-demo-20180724-firebase-adminsdk-g7o1b-afa0269793.json
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toolchain?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


zjc:
  kafka:
    bootstrap-servers: localhost:9092
    topic: test-topic-1
    consumer:
      group-id: test-consumer-group

data:
  file:
    orb:
      basedir: C:\\Users\\zhijiang\\Documents\\Projects\\toolchain\\Crosslink Scenario Data\\


file:
  upload:
    basedir: C:\\upload-dir

simulation:
  step: 30

mininet:
  ip: 192.168.1.2
  port: 2222